server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 /login;
    }

    location / {
        try_files $uri $uri.html $uri/ /404.html;
    }
}
